name: Grant Application
description: Propose a project to the Zama Grant Program
title: "[GRANT] <enter project name>"
labels: ["grant-app-tpl", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        <!-- grant-application-tpl:v1 -->
        ## Zama Grant Program: Application
        Please give us as much information as possible on the project you would like to submit. You can find inspiration from our existing list of grants.

  - type: dropdown
    id: library
    attributes:
      label: Library targeted
      description: 'What library is the project targeting?'
      options:
        - Select a library
        - fhEVM
        - TFHE-rs
        - Concrete
        - Concrete ML
        - Research
    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: 'Propose an overview: Short description of your project'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: 'Propose a Description: Complete and detailed description of your project'
    validations:
      required: true

  - type: input
    id: reward
    attributes:
      label: Reward
      description: 'Give an estimate of the grant you would like to received for this project (will be later validated by the Zama team)'
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: Related links and references
      description: 'Give any links that could help us learn more about your project (papers, articles, existing implementation…)'
    validations:
      required: true
